title: Somekind of what
author: My User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Apibudinimas blogo

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
